In [122]:
import numpy as np
import matplotlib.pyplot as plt

# 1. Get the numpy version and show numpy build configuration

In [8]:
print("NumPy version:", np.__version__)

NumPy version: 1.26.4


In [10]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anaconda3=/usr/local/src/c

# 2. Get help on the add function

In [14]:
print("\nHelp on np.add function:")
help(np.add)


Help on np.add function:
Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, 

#  3. Test whether none of the elements of a given array is zero

In [17]:
arr=np.array([1,2,3,4,5,6,7,8])
np.all(arr)

True

#  4. Test whether any of the elements of a given array is non-zero

In [20]:
arr=np.array([0,0,0])
np.any(arr)

False

# 5. Test element-wise for finiteness (not infinity or NaN)

In [23]:
arr2 = np.array([1, 0, -10.5,3.1415,np.inf, -np.inf, np.nan])
arr2
print("Finiteness test:", np.isfinite(arr2))

Finiteness test: [ True  True  True  True False False False]


# 6. Test element-wise for positive or negative infinity

In [26]:
print("Infinity test:", np.isinf(arr2))

Infinity test: [False False False False  True  True False]


# 7. Test element-wise for NaN of a given array

In [30]:
print("NaN test:", np.isnan(arr2))

NaN test: [False False False False False False  True]


# 8. Test element-wise for complex, real numbers, and scalar type

In [33]:
arr3 = np.array([1, 2+3j, 5.0])
print("Is complex:", np.iscomplex(arr3))
print("Is real:", np.isreal(arr3))
print("Is scalar :", np.isscalar(3.5))

Is complex: [False  True False]
Is real: [ True False  True]
Is scalar (check 3.5): True


# 9. Element-wise comparison of two arrays

In [36]:
x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
print("Greater:", np.greater(x, y))
print("Greater_equal:", np.greater_equal(x, y))
print("Less:", np.less(x, y))
print("Less_equal:", np.less_equal(x, y))

Greater: [False False  True]
Greater_equal: [False  True  True]
Less: [ True False False]
Less_equal: [ True  True False]


# 10. Create array with values 1,7,13,105 and find memory size

In [39]:
arr = np.array([1, 7, 13, 105])
print("Array:", arr)
print(arr.itemsize)  
print("Memory size (bytes):", arr.nbytes)

Array: [  1   7  13 105]
8
Memory size (bytes): 32


# 11. Create an array of 10 zeros, 10 ones, 10 fives

In [42]:
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10, 5)
print("\nZeros:", zeros)
print("Ones:", ones)
print("Fives:", fives)


Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Fives: [5 5 5 5 5 5 5 5 5 5]


# 12. Create an array of integers from 30 to 70

In [47]:
arr = np.arange(30, 71)
print("Array 30 to 70:", arr)

Array 30 to 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


# 13. Create an array of all even integers from 30 to 70

In [50]:
arr = np.arange(30, 71, 2)
print("Even array 30 to 70:", arr)

Even array 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# 14. Create a 3x3 identity matrix

In [53]:
identity = np.identity(3)
print("\n3x3 Identity Matrix:\n", identity)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 15. Generate a random number between 0 and 1

In [56]:
rand_num = np.random.rand()
print("Random number between 0 and 1:", rand_num)

Random number between 0 and 1: 0.3909129560912834


# 16. Generate an array of 15 random numbers from a standard normal distribution

In [59]:
rand_arr = np.random.randn(15)
print("15 Random numbers from normal distribution:", rand_arr)


15 Random numbers from normal distribution: [-0.9004996   0.85478548  0.68887507  0.42180643 -0.60675659 -0.97403714
 -0.85596488  1.58497278  0.4042567   0.45680799  0.88873677 -1.54191788
  0.87160546  0.96846208 -1.35405096]


# 17. Create a vector with values ranging from 15 to 55 and print all values except the first and last

In [62]:
vec = np.arange(15, 56)
print("\nVector 15 to 55:", vec)
print("Without first and last:", vec[1:-1])



Vector 15 to 55: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Without first and last: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


# 18. Create a 3x4 array and iterate over it

In [65]:
arr1 = np.arange(12).reshape(3, 4)  
print("3x4 Array:\n", arr1)

print("Iterating row-wise:")
for row in arr1:
    print(row)

print("Iterating element-wise:")
for element in np.nditer(arr1):   
    print(element, end=" ")

3x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Iterating row-wise:
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
Iterating element-wise:
0 1 2 3 4 5 6 7 8 9 10 11 

# 19. Create a vector of length 10 with values evenly distributed between 5 and 50

In [68]:
vec1 = np.linspace(5, 50, 10)  # 10 points between 5 and 50
print("\n\nVector with evenly spaced values between 5 and 50:\n", vec1)



Vector with evenly spaced values between 5 and 50:
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


# 20. Create a vector 0–20 and change the sign of numbers from 9 to 15

In [71]:
vec2 = np.arange(21)  
vec2[(vec2 >= 9) & (vec2 <= 15)] *= -1  
print("\nVector 0–20 with sign changed from 9–15:\n", vec2)


Vector 0–20 with sign changed from 9–15:
 [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


# 21. Create a vector of length 5 filled with arbitrary integers from 0 to 10

In [74]:
vec3 = np.random.randint(0, 11, 5)   
print("\nRandom vector of length 5:\n", vec3)


Random vector of length 5:
 [6 0 8 8 5]


# 22. Multiply the values of two given vectors

In [79]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
product = np.multiply(v1, v2)   
print("\nMultiplication of vectors:", product)


Multiplication of vectors: [ 4 10 18]


# 23 Create a 3x4 matrix filled with values from 10 to 21

In [82]:
matrix1 = np.arange(10, 22).reshape(3, 4)
print("3x4 Matrix:\n", matrix1)

3x4 Matrix:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# 24. Find number of rows and columns of a given matrix


In [86]:
rows, cols = matrix1.shape
print("Rows:", rows, "Columns:", cols)

Rows: 3 Columns: 4


# 25. Create a 3x3 identity matrix


In [89]:
identity_mat = np.identity(3)
print("Identity Matrix:\n", identity_mat)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 26. Create a 10x10 matrix, borders = 1, inside = 0

In [154]:
border_matrix = np.ones((10, 10))
border_matrix[1:-1, 1:-1] = 0
print("Border Matrix:\n", border_matrix)


Border Matrix:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


 # 27. Create a 5x5 zero matrix with diagonal elements = 1,2,3,4,5


In [99]:
diag_matrix = np.diag([1, 2, 3, 4, 5])
print("Diagonal Matrix:\n", diag_matrix)


Diagonal Matrix:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]



# 28. Create a 4x4 matrix with 0 & 1 staggered, diagonal = 0

In [102]:
stagger_matrix = np.indices((4, 4)).sum(axis=0) % 2
np.fill_diagonal(stagger_matrix, 0)
print("Staggered Matrix:\n", stagger_matrix)

Staggered Matrix:
 [[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


# 29. Create a 3x3x3 array with arbitrary values

In [106]:
array3d = np.random.randint(0, 10, (3, 3, 3))
print("3x3x3 Array:\n", array3d)

3x3x3 Array:
 [[[2 2 4]
  [6 2 6]
  [2 6 5]]

 [[4 8 2]
  [2 9 7]
  [6 5 0]]

 [[6 1 3]
  [0 5 8]
  [8 1 4]]]


# 30. Compute sum of all elements, sum of each column and sum of each row

In [109]:
print("Sum of all elements:", matrix1.sum())
print("Sum of each column:", matrix1.sum(axis=0))
print("Sum of each row:", matrix1.sum(axis=1))

Sum of all elements: 186
Sum of each column: [42 45 48 51]
Sum of each row: [46 62 78]


# 31. Compute inner product of two vectors


In [114]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("Inner Product:", np.inner(v1, v2))


Inner Product: 32


# 32. Add a vector to each row of a given matrix


In [117]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
vec = np.array([10, 20, 30])
print("Matrix + Vector:\n", mat + vec)


Matrix + Vector:
 [[11 22 33]
 [14 25 36]]


# 33. Compute x, y for sine curve & plot


x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)
plt.plot(x, y)
plt.title("Sine Curve")
plt.show()


# 34. Convert numpy dtypes to native python types


In [129]:
n = np.int32(100)
print("Python type:", type(n.item()))

Python type: <class 'int'>


# 35. Find missing data in array

In [135]:
arr = np.array([1, 2, np.nan, 4, 5, np.nan])
print("Missing Data:", np.isnan(arr))

Missing Data: [False False  True False False  True]


 # 36. Sort array by row & column


In [138]:
arr2 = np.array([[3, 7, 9], [1, 5, 2]])
print("Row-wise sort:\n", np.sort(arr2, axis=1))
print("Column-wise sort:\n", np.sort(arr2, axis=0))

Row-wise sort:
 [[3 7 9]
 [1 2 5]]
Column-wise sort:
 [[1 5 2]
 [3 7 9]]


# 37. Extract numbers less/greater than a given number

In [147]:
arr3 = np.array([1, 5, 8, 12, 20])
print("Less than 10:", arr3[arr3 < 10])
print("Greater than 10:", arr3[arr3 > 10])


Less than 10: [1 5 8]
Greater than 10: [12 20]


# 38. Replace numbers equal, less, greater than a given number


In [144]:
arr4 = np.array([5, 10, 15, 20])
arr4[arr4 == 10] = -1
arr4[arr4 < 10] = -2
arr4[arr4 > 10] = -3
print("Replaced Array:", arr4)

Replaced Array: [-2 -2 -3 -3]


# 39. Create equal shape & type array of a given array


In [151]:
arr5 = np.arange(6).reshape(2, 3)
arr_equal = np.empty_like(arr5)
print("Equal Shape Array:\n", arr_equal)

Equal Shape Array:
 [[1 5 2]
 [3 7 9]]


# 40. Create a 3D array with shape (3,5,4)


In [169]:
array3d_var = np.zeros((3, 5, 4))
print("3D Array Shape:", array3d_var.shape)


3D Array Shape: (3, 5, 4)


 # 41. Multiply two arrays element-by-element


In [172]:
arrA = np.array([[1, 2], [3, 4]])
arrB = np.array([[2, 2], [2, 2]])
print("Element-wise multiplication:\n", arrA * arrB)


Element-wise Multiplication:
 [[2 4]
 [6 8]]
